/**
 * generate_portfolio.js
 * Generates assets/js/portfolio-data.js from the assets folder structure.
 * Run with: node generate_portfolio.js
 */
const fs = require('fs');
const path = require('path');

const base = __dirname;

function getImages(dir) {
    if (!fs.existsSync(dir)) return [];
    const exts = ['.jpg', '.jpeg', '.png', '.gif', '.webp'];
    return fs.readdirSync(dir)
        .filter(f => exts.includes(path.extname(f).toLowerCase()))
        .map(f => ({
            file: f,
            path: path.join(dir, f).replace(base + path.sep, '').replace(/\\/g, '/')
        }));
}

function getVideos(dir) {
    if (!fs.existsSync(dir)) return [];
    const exts = ['.mp4', '.webm', '.mov'];
    return fs.readdirSync(dir)
        .filter(f => exts.includes(path.extname(f).toLowerCase()))
        .map(f => ({
            name: path.basename(f, path.extname(f)),
            path: path.join(dir, f).replace(base + path.sep, '').replace(/\\/g, '/')
        }));
}

// ---- GRAPHIC DESIGN ----
const graphicBase = path.join(base, 'assets/images/portfolio/graphic-design');
const graphicCategories = fs.existsSync(graphicBase)
    ? fs.readdirSync(graphicBase).filter(f => fs.statSync(path.join(graphicBase, f)).isDirectory())
    : [];

const graphicDesign = graphicCategories.map(cat => {
    const catPath = path.join(graphicBase, cat);
    const subDirs = fs.readdirSync(catPath).filter(f => fs.statSync(path.join(catPath, f)).isDirectory());

    const projects = subDirs.map(proj => {
        const projPath = path.join(catPath, proj);
        const images = getImages(projPath);
        return {
            name: proj,
            images
        };
    });

    // Also include any images directly in the category folder (e.g. logo)
    const directImages = getImages(catPath);
    if (directImages.length > 0 && projects.length === 0) {
        projects.push({ name: cat, images: directImages });
    }

    return { category: cat, projects };
});

// ---- UX/UI ----
const uxBase = path.join(base, 'assets/images/portfolio/ux-ui');
const uxDirs = fs.existsSync(uxBase)
    ? fs.readdirSync(uxBase).filter(f => fs.statSync(path.join(uxBase, f)).isDirectory())
    : [];

const uxUi = uxDirs.map(proj => {
    const projPath = path.join(uxBase, proj);
    const images = getImages(projPath);
    return { name: proj, images };
});

// ---- VIDEOS ----
const videoBase = path.join(base, 'assets/videos/portfolio/video-edits');
const videos = getVideos(videoBase);

// Output
const graphicCount = graphicDesign.reduce((acc, cat) => acc + cat.projects.reduce((a, p) => a + p.images.length, 0), 0);
const uxCount = uxUi.reduce((acc, p) => acc + p.images.length, 0);
const videoCount = videos.length;

const output = `// portfolio-data.js — Auto-generated by generate_portfolio.js
// Run "node generate_portfolio.js" to regenerate when adding new assets.

const portfolioData = {
    // Auto-computed counts — updated every time you run generate_portfolio.js
    counts: {
        graphicDesign: ${graphicCount},
        videoEdits: ${videoCount},
        uiConcepts: ${uxCount}
    },
    graphicDesign: ${JSON.stringify(graphicDesign, null, 4)},
    uxUi: ${JSON.stringify(uxUi, null, 4)},
    videos: ${JSON.stringify(videos, null, 4)}
};
if (typeof module !== 'undefined' && module.exports) module.exports = portfolioData;
`;

fs.writeFileSync(path.join(base, 'assets/js/portfolio-data.js'), output);
console.log(`\nGenerated OK:`);
console.log(`  Graphic Design: ${graphicCount} images`);
console.log(`  Video Edits:    ${videoCount} videos`);
console.log(`  UI Concepts:    ${uxCount} screens`);
graphicDesign.forEach(cat => console.log(`    Graphic → ${cat.category}: ${cat.projects.map(p => p.name + ' (' + p.images.length + ')').join(', ')}`));
uxUi.forEach(p => console.log(`    UX/UI → ${p.name}: ${p.images.length}`));
